### ISSUE TITLE
[BUG] Sequence Token Not Received on Web Platform

### ISSUE THREAD

**Issue by khurram72** [Zsmerritt/Flutter_AWS_CloudWatch#9]
Whenever I try to make a log request to CloudWatch using flutter ```web``` client, the first request is successfully logged to the cloudwatch as no sequence token is required for new log stream.

However, any subsequent log request to same logStream throws an error ```CloudWatchException - message: null```.

So I tried to debug the things and found out that only ```statusCode``` value is available on ```web``` and all the other fields remains ```null``` as in below ```AwsResponse``` class.

```dart
class AwsResponse{
  int statusCode;
  String? type;
  String? message;
  String? nextSequenceToken;
  String? expectedSequenceToken;
  String? raw;
}
```

```Sample Response``` on ```web```

```json
{
"statusCode" : 400,
"type" : null,
"message" : null,
"nextSequenceToken" : null,
"expectedSequenceToken" : null,
"raw" : null
}
```

Due to this the ```nextSequenceToken``` is null and on next request we get a ```statusCode``` as ```400``` which implies ```nextSequenceToken``` was not included in the request, and now the error handler ```_handleError``` is unable to resolve the error response as  ```expectedSequenceToken``` is also null.

Hence, only single request is sent to the cloudwatch and other logs doesn't append to the same logStream.

Could you please have a look into the issue, I am trying to figure out if it's an issue with ```AwsRequest``` or ```universal_io```.

Your thoughts would be really helpful on this.

**Comment by Zsmerritt** [comment]
Interesting. I haven't actually tested with flutter web. The only reason all of those fields would be null is if `response.contentLength` is 0. 

I dont think its an issue with `aws_request`. All that package really does is the SigV4 signing component of the API request and returns the response.

My guess is that on the web, the response comes back differently and isnt being parsed correctly. This leads to those values being null and all following requests to fail. If the response body truly is null it may be a bug with `universal_io` but I would doubt that. Ill do some testing this weekend with a web app and put out a patch

**Comment by khurram72** [comment]
Thanks for your response, would wait for your findings and patch till then, meanwhile, I was able to looking into the package: ```aws_logs_api: ^1.0.0``` which works well with ```web``` platform, if you would like to have a look into <a href="https://github.com/agilord/aws_client/tree/master/generated/aws_logs_api">this</a>, if it helps.

**Comment by Zsmerritt** [comment]
Thanks for finding that! Ill check out their implementation for web stuff and comment when I have a solution

**Comment by Zsmerritt** [comment]
I did some digging and it looks like universal_io has a bug where if you include headers that chrome rejects, the response stream returns `Bad state: Stream has already been listened to.` which in turn means the response object cant be parsed. Ill post an issue there to let them know. 

I removed the headers that chrome had issues with and tested everything on a mobile device and chrome. Everything seemed to work as expected. I pushed a new version of aws_request that fixes the headers and updated aws_cloudwatch with the new version of aws_request. 

Let me know if that fixes the issue on your end. Thanks for your help with this and with development :)

**Comment by Zsmerritt** [comment]
I went back to dig a little more with the old version to provide more details for the bug and I cant reproduce it anymore. I dont know what changed. 

If you run into it with the new version still can you post what you're seeing in the network and console tabs?

**Comment by khurram72** [comment]
Thanks for your comment, I will check this and get back to you!

**Comment by khurram72** [comment]
Unfortunately, the issue still persist for me even on latest release and the response is still not parsed correctly, please find attached the screenshots from Console and Network Tabs.
 
Context ```(please refer screenshots)```: I am trying to make cloudwatch log requests using my aws  ```temp credentials```, the counter ```increment button ``` adds a log to my general log group, while the ```red cross button``` generates an uncaught error that gets logged to another error log group on aws.

Also, the 100 instance of CloudHandler as seen in Console Screenshot, is some large request I was simulating under the build method as soon as page renders, which in-turn is a first request for log, followed by a second request sent via increment button which fails due to sequence token missing.

The sequence token error is thrown as seen in network tab screenshot.

<table>
<tr>
<th>Console tab</th>
<th>Network tab</th>
</tr>
<tr>
<td><img width="1680" alt="Screenshot 2022-01-09 at 3 28 52 PM" src="https://user-images.githubusercontent.com/82940795/148678970-325c32a7-0801-4229-9d5a-932f43566b46.png">
</td>
<td><img width="1680" alt="Screenshot 2022-01-09 at 3 30 39 PM" src="https://user-images.githubusercontent.com/82940795/148678222-df12fd29-20eb-4929-83cd-7372fe1d8309.png"></td>
</tr>
</table>

Thanks for being responsive through this issue.

**Comment by Zsmerritt** [comment]
Thanks for getting back to me. Thats really interesting. I wasnt getting any response body back when I was having this issue but the response content length header was something like 90. Thats why I was thinking your intuition was right with universal_io.

Can you post the logging file you used to generate that? Basically your version of example 3.  No need to share the `main.dart`.

If you can put in a debugger into `aws_cloudwatch.dart` in the CloudWatch `_log` function and then call `this._setVerbosity(3)` before anything is sent I would appreciate it. That will output super detailed information to standard out. Redact whatever you dont feel comfortable sharing and attach a text file.

As a side note, Im moving away from universal_io to just the standard http package. Ive had an update for aws_request in to works that included that for a while but I just got it out tonight. Im going to work on getting aws_cloudwatch using it tomorrow. Given your screenshots I dont think that will fix this issue but it might be worth testing. When I have a branch ready Ill let you know

**Comment by khurram72** [comment]
Please checkout the errorLog file ```errorLog.dart```

```dart 

import 'package:aws_cloudwatch/aws_cloudwatch.dart';
import 'package:intl/intl.dart';

String _AWS_ACCESS_KEY_ID = '';
String _AWS_SECRET_ACCESS_KEY = '';
String _AWS_SESSION_TOKEN = '';
String _Region = '';
String _LogGroup = '/some/path/to/log';
String _ErrorGroup = '/some/path/to/error';

CloudWatchHandler logging = CloudWatchHandler(
  awsAccessKey: _AWS_ACCESS_KEY_ID,
  awsSecretKey: _AWS_SECRET_ACCESS_KEY,
  region: _Region,
  awsSessionToken: _AWS_SESSION_TOKEN,
  delay: const Duration(milliseconds: 200),
);

String logStreamName = '';

// You may want to edit this function to suit your needs
String _getLogStreamName() {
  if (logStreamName == "") {
    logStreamName = DateFormat("yyyy-MM-dd HH-mm-ss").format(
      DateTime.now().toUtc(),
    );
  }
  return logStreamName;
}

void log(String logString, {isError = false}) {
  print(logging);
  logging.log(
    msg: logString,
    logGroupName: isError ? _ErrorGroup : _LogGroup,
    logStreamName: _getLogStreamName(),
  );
}

void logFlutterSystemError(dynamic logString, dynamic stackTrace) async {
  log(
    'Auto Captured Error: ${logString.toString()}\n\n'
    'Auto Captured Stack Trace:\n${stackTrace.toString()}',
    isError: true,
  );
}
```

```detailed log```

```
Instance of 'CloudWatchHandler'
CloudWatch INFO: Attempting to log many
CloudWatch INFO: Added messages to log stack
CloudWatch INFO: Generating LogStream
CloudWatch Info: LogStream creation status code: 200
CloudWatch INFO: Got LogStream
CloudWatch INFO: Generating CloudWatch request body
CloudWatch INFO: Generated jsonBody with 1 logs: {"logEvents":[{"timestamp":1641727654140,"message":"_counter incremented 1"}],"logGroupName":"/some/path/to/log","logStreamName":"2022-01-09 11-27-34"}
CloudWatch Info: AwsResponse - statusCode: 200
Instance of 'CloudWatchHandler'
CloudWatch INFO: Attempting to log many
CloudWatch INFO: Added messages to log stack
CloudWatch INFO: Generating CloudWatch request body
CloudWatch INFO: Generated jsonBody with 1 logs: {"logEvents":[{"timestamp":1641727661650,"message":"_counter incremented 2"}],"logGroupName":"/some/path/to/log","logStreamName":"2022-01-09 11-27-34"}
CloudWatch ERROR: AwsResponse - statusCode: 400
CloudWatch ERROR: Failed making AwsRequest. Retrying 1
CloudWatch INFO: Generating CloudWatch request body
CloudWatch INFO: Generated jsonBody with 1 logs: {"logEvents":[{"timestamp":1641727661650,"message":"_counter incremented 2"}],"logGroupName":"/some/path/to/log","logStreamName":"2022-01-09 11-27-34"}
CloudWatch ERROR: AwsResponse - statusCode: 400
CloudWatch ERROR: Failed making AwsRequest. Retrying 2
CloudWatch INFO: Generating CloudWatch request body
CloudWatch INFO: Generated jsonBody with 1 logs: {"logEvents":[{"timestamp":1641727661650,"message":"_counter incremented 2"}],"logGroupName":"/some/path/to/log","logStreamName":"2022-01-09 11-27-34"}
CloudWatch ERROR: AwsResponse - statusCode: 400
CloudWatch ERROR: Failed making AwsRequest. Retrying 3
CloudWatch ERROR: Failed to send logs
Instance of 'CloudWatchHandler'
CloudWatch INFO: Attempting to log many
CloudWatch INFO: Added messages to log stack
CloudWatch INFO: Generating LogStream
CloudWatchException - message: null
Error: CloudWatchException - message: null
    at Object.throw_ [as throw] (http://localhost:65441/dart_sdk.js:5063:11)
at http://localhost:65441/packages/aws_web_app/main.dart.lib.js:421:19
    at Generator.next (<anonymous>)
    at runBody (http://localhost:65441/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:65441/dart_sdk.js:40242:7)
at http://localhost:65441/packages/aws_web_app/main.dart.lib.js:418:73
    at _RootZone.runBinary (http://localhost:65441/dart_sdk.js:40066:59)
    at http://localhost:65441/dart_sdk.js:40601:20
    at async._CustomZone.new.[_processUncaughtError] (http://localhost:65441/dart_sdk.js:39493:9)
    at async._CustomZone.new.handleUncaughtError (http://localhost:65441/dart_sdk.js:39715:34)
    at Function._propagateToListeners (http://localhost:65441/dart_sdk.js:35489:30)
    at _Future.new.[_completeWithValue] (http://localhost:65441/dart_sdk.js:35437:23)
    at http://localhost:65441/dart_sdk.js:35458:35
    at _rootRun (http://localhost:65441/dart_sdk.js:40486:14)
    at async._CustomZone.new.run (http://localhost:65441/dart_sdk.js:39729:14)
    at async._CustomZone.new.runGuarded (http://localhost:65441/dart_sdk.js:39643:14)
    at async._AsyncCallbackEntry.new.callback (http://localhost:65441/dart_sdk.js:39691:33)
    at Object._microtaskLoop (http://localhost:65441/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:65441/dart_sdk.js:40336:13)
    at http://localhost:65441/dart_sdk.js:35811:9
CloudWatch Info: LogStream creation status code: 200
CloudWatch INFO: Got LogStream
CloudWatch INFO: Generating CloudWatch request body
CloudWatch INFO: Generated jsonBody with 1 logs: {"logEvents":[{"timestamp":1641727662254,"message":"Auto Captured Error: CloudWatchException - message: null\n\nAuto Captured Stack Trace:\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\npackages/aws_cloudwatch/aws_cloudwatch.dart 652:9                             [_checkError]\npackages/aws_cloudwatch/aws_cloudwatch.dart 636:9                             _log\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>\ndart-sdk/lib/async/zone.dart 1436:47                                          _rootRunUnary\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\ndart-sdk/lib/async/future_impl.dart 160:18                                    handleValue\ndart-sdk/lib/async/future_impl.dart 767:44                                    handleValueCallback\ndart-sdk/lib/async/future_impl.dart 796:13                                    _propagateToListeners\ndart-sdk/lib/async/future_impl.dart 602:5                                     [_completeWithValue]\ndart-sdk/lib/async/future_impl.dart 640:7                                     <fn>\ndart-sdk/lib/async/zone.dart 1428:13                                          _rootRun\ndart-sdk/lib/async/zone.dart 1328:19                                          run\ndart-sdk/lib/async/zone.dart 1236:7                                           runGuarded\ndart-sdk/lib/async/zone.dart 1276:23                                          callback\ndart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop\ndart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>\n"}],"logGroupName":"/some/path/to/error","logStreamName":"2022-01-09 11-27-34"}
CloudWatch Info: AwsResponse - statusCode: 200

```

sure thanks, I will wait, and give it a try once its out.

**Comment by khurram72** [comment]
Just a quick follow up on the issue, so I tried overriding the dependency of ```aws_request``` with your latest release of ```aws_request: ^0.3.0``` & updated my cached copy of ```aws_cloudwatch``` by replacing & modifying all the usage of ```universal_io``` with ```http``` package as an experimentation and I am glad to inform you that I was able to make successful requests to aws using my web app 🥳

That's a really great move of yours, switching to ```http``` from ```universal_io``` .

There really seems to be something wrong with ```universal_io``` at-least on flutter ```web```.

I will wait for your new release of ```aws_cloudwatch```.

Really appreciate all your efforts in making both of this amazing packages ``` aws_request``` & ```aws_cloudwatch```.

More power to you! 🙌🙌🙌

Thanks!

**Comment by Zsmerritt** [comment]
Glad to hear that the new update solved the issue! Thanks for putting in a PR with those changes. I left some comments on a couple things. 

I really appreciate your help in getting to the bottom of this! With this new update to `aws_request` it should be way easier to write unit tests for all this code so that we run into this kind of stuff less often.

**Comment by Zsmerritt** [comment]
Version `0.4.7` has been released! Thanks for you help with this! I appreciate it :)

**Comment by khurram72** [comment]
Really appreciate your effort throughout the development, I will look forward to contribute more in near future, Thanks! :)
